<a href="https://colab.research.google.com/github/samyff12/Modelos-estadisticos/blob/main/ModEst_Lab1_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Laboratorio 1.
## Manejo de matrices
El objetivo de este laboratorio es aprender cómo se realizan las principales operaciones del álgebra lineal usando de Python, la librería $\texttt{numpy}$. 

## Actividad 1. Introducción
En esta actividad creamos una matriz $A_{(2\times 3)}$ y encontramos sus características. Asimismo, vemos como se recorre y extraen los valores de su interior.

In [2]:
import numpy as np

# Definiendo una matriz
A = np.array([[1,2,3], [4,5,6]])
print("La matriz: \n", A, "\n")
nrow, ncol = A.shape #  Dimensión de la matriz                        matrices de mas de dos dimensiones se llaman tensores
print("Número de filas: ", nrow)
print("Número de columnas: ", ncol)
print("La primera fila: ", A[0])
print("La primera columna: ", A[:,0])
print("El primer elemento: ", A[0,0])

# Recorriendo la matriz
print("Sus elementos escritos en orden a aparición:")
for i in range(nrow):
  for j in range(ncol):
    print(A[i,j])

La matriz: 
 [[1 2 3]
 [4 5 6]] 

Número de filas:  2
Número de columnas:  3
La primera fila:  [1 2 3]
La primera columna:  [1 4]
El primer elemento:  1
Sus elementos escritos en orden a aparición:
1
2
3
4
5
6


## Actividad 2. La traspuesta y el producto escalar
Ahora, además de $A$ creamos la matriz $B_{(3\times 2)}$.

In [7]:
# Calculando su traspuesta
print("La traspuesta:\n", A.T)

# Producto escalar
B = np.array([[7,8], [9,10], [11,12]])
print("La matriz B:")
print(B)
C = np.dot(A,B) # También llamado "Producto punto"
print("AB=\n", C)

La traspuesta:
 [[1 4]
 [2 5]
 [3 6]]
La matriz B:
[[ 7  8]
 [ 9 10]
 [11 12]]
AB=
 [[ 58  64]
 [139 154]]


## Actividad 3. El vector y matriz de unos

In [ ]:
# Vector de unos
j = np.ones(10, dtype=np.int64)
j = j[:, np.newaxis] # Note que debemos transformarlo en una matriz
# en python vector es solo un arreglo de numeros unidimensional, pero en la teoria cuando se habla de vector se habla de un vector columna

print(j)
# Matriz de unos
J = j.dot(j.T)
print(J)

[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]]
[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [8]:
np.ones(10, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## Actividad 4. Matrices simétricas

In [ ]:
# Un par de matrices simétricas
print("A:\n", A)
print("AA^t:\n", np.dot(A, A.T))
print("A^tA:\n", np.dot(A.T, A))

A:
 [[1 2 3]
 [4 5 6]]
AA^t:
 [[14 32]
 [32 77]]
A^tA:
 [[17 22 27]
 [22 29 36]
 [27 36 45]]


## Actividad 5. Independencia lineal
Importamos la librería $\texttt{linalg}$ de $\texttt{numpy}$, especializada en álgebra lineal. La matriz $A_{(3\times 3)}$ está formada claramente por un conjunto de vectores linealmente dependientes. Por su parte, la matriz $B_{(3\times 3)}$ la forman vectores que esperamos linealmente independientes por haber sido generados aleatoriamente de una normal estándar. Comprobamos esto calculando los rangos.

In [ ]:
from numpy import linalg as la

np.random.seed(100)

# Vectores linealmente independientes y dependientes
A = np.array([[2,4,6], [4,8,12], [8,16,24]])
B = np.array(np.random.standard_normal(9)).reshape((3,3))
print("La matriz A:\n", A)
print("La matriz B:\n", B)

# Rango
print("r(A)=", la.matrix_rank(A))
print("r(B)=", la.matrix_rank(B))
C = np.dot(A.T, A)
print("La matriz C=A^tA:\n", C)
print("r(C)=", la.matrix_rank(C))


La matriz A:
 [[ 2  4  6]
 [ 4  8 12]
 [ 8 16 24]]
La matriz B:
 [[-1.74976547  0.3426804   1.1530358 ]
 [-0.25243604  0.98132079  0.51421884]
 [ 0.22117967 -1.07004333 -0.18949583]]
r(A)= 1
r(B)= 3
La matriz C=A^tA:
 [[ 84 168 252]
 [168 336 504]
 [252 504 756]]
r(C)= 1


## Actividad 6. Otras matrices importantes

In [ ]:
print("La matriz de ceros")
Z = np.zeros((5,5))
print(Z)

print("Una matriz cuadrada cualquiera A")
A = np.round(np.array(np.random.standard_normal(25)).reshape((5,5)),2)
print(A)
print("Su diagonal")
print(A.diagonal())

print("Una matriz diagonal")
B = np.diag([1,2,3,4,5])
print(B)

print("La matriz identidad")
I = np.diag(np.ones(3, dtype=np.int64))
print(I)

print("Una matriz idempotente")
A = np.array([[2,-3,-5], [-1,4,5], [1,-3,-4]])
print("A:")
print(A)
print("AA:")
print(A.dot(A))

print(la.matrix_rank(A))


La matriz de ceros
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Una matriz cuadrada cualquiera A
[[-0.75 -1.3   0.1  -0.42 -1.19]
 [-0.37 -1.27  1.59  0.69 -1.96]
 [-0.13 -1.54  2.05 -1.4  -1.1 ]
 [-0.24 -1.43  0.95 -0.02  0.89]
 [ 0.76 -1.5  -1.19  1.3   0.95]]
Su diagonal
[-0.75 -1.27  2.05 -0.02  0.95]
Una matriz diagonal
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
La matriz identidad
[[1 0 0]
 [0 1 0]
 [0 0 1]]
Una matriz idempotente
A:
[[ 2 -3 -5]
 [-1  4  5]
 [ 1 -3 -4]]
AA:
[[ 2 -3 -5]
 [-1  4  5]
 [ 1 -3 -4]]
2


## Actividad 7. Ilustremos la tarea
Recordamos que, llegados a este punto, la tarea era demostrar que si $A$ es idempotente, entonces $I-A$ también lo es. Debemos probar que $(I-A)(I-A)=(I-A)$, entonces $(I-A)(I-A) = II-IA-AI+AA = I-A-A+A = I-A$, ya que $AA=A$ debido a su idempotencia. Su ilustración entonces: 

In [ ]:
B=I-A
print(B)
C = np.dot(B, B)
print(C)

[[-1  3  5]
 [ 1 -3 -5]
 [-1  3  5]]
[[-1  3  5]
 [ 1 -3 -5]
 [-1  3  5]]


## Actividad 8. La matriz inversa
(o la inversa de una matriz)

In [ ]:
# Una que debería tener inversa...
print("A")
A = np.round(np.array(np.random.standard_normal(25)).reshape((5,5)),2)
print(A)
print("r(A)=", la.matrix_rank(A))

print("La inversa de A")
A_i = la.inv(A)
print(A_i)
print("AA^{-1}")
R = np.dot(A, A_i)
print(R.round())

# Una que no tiene...
# Bi = la.inv(B)

# Veamos sus determinantes
Ad = la.det(A)
Bd = la.det(B)
print("Determinante de A:", Ad)
print("Determinante de B:", Bd)

A
[[-0.34  0.53 -0.37  0.48 -1.43]
 [ 0.41 -0.83  0.42 -0.16  1.24]
 [ 1.66 -0.66  3.47  0.39  0.33]
 [-0.31 -1.42 -0.62 -0.11  0.95]
 [-0.98 -1.09 -0.24 -0.6  -0.98]]
r(A)= 5
La inversa de A
[[ 10.93408416  22.7010763   -3.12810329  -9.59057062   2.41865112]
 [ -2.82676604  -5.29907942   0.58322133   1.66090897  -0.7737311 ]
 [ -4.94195655  -9.95357677   1.60913401   3.98006691  -0.98301993]
 [ -3.7047276  -10.11018681   1.62651678   5.17188038  -1.8253411 ]
 [ -4.31155241  -8.17968133   1.08951811   3.60206545  -1.22018547]]
AA^{-1}
[[ 1. -0. -0. -0.  0.]
 [-0.  1.  0. -0.  0.]
 [ 0. -0.  1. -0.  0.]
 [-0.  0. -0.  1. -0.]
 [-0. -0.  0.  0.  1.]]
Determinante de A: 0.3435172370999998
Determinante de B: 0.0


## Actividad 9. Valores y vectores propios

In [ ]:
# Valores (v) y vectores propios (w)
A = np.array([[2,0,0,0],[1,2,0,0],[0,1,3,0],[0,0,1,3]])
print("A:\n", A)
print("r(A)=", la.matrix_rank(A))
v, W = la.eig(A)
print("Valores propios:\n", v.round(1))
print("Vectores propios:\n", W.round(1))

idx_vector = 0
# Raíces del polinomio característico
I = np.eye(4)
print("Identidad:\n", I)
R = A - v[idx_vector]*(I)
print("Matriz del polinomio característico:\n", R)
print("Su determinante:\n", la.det(R))

# Verificando los vectores propios
C = R.dot(W[:, idx_vector])
print("C:", C.round(5))

# La traza
print(A.trace())

# Ahora una matriz idempotente
B = np.array([[2,-3,-5], [-1,4,5], [1,-3,-4]])
print("Matriz idempotente B:\n", B)
print("Su traza:", B.trace())
print("Su rango:", la.matrix_rank(B))
v1, W1 = la.eig(B)
print("Sus valores propios: ", v1.round())

A:
 [[2 0 0 0]
 [1 2 0 0]
 [0 1 3 0]
 [0 0 1 3]]
r(A)= 4
Valores propios:
 [3. 3. 2. 2.]
Vectores propios:
 [[ 0.   0.   0.   0. ]
 [ 0.   0.   0.6 -0.6]
 [ 0.   0.  -0.6  0.6]
 [ 1.  -1.   0.6 -0.6]]
Identidad:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Matriz del polinomio característico:
 [[-1.  0.  0.  0.]
 [ 1. -1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]]
Su determinante:
 0.0
C: [0. 0. 0. 0.]
10
Matriz idempotente B:
 [[ 2 -3 -5]
 [-1  4  5]
 [ 1 -3 -4]]
Su traza: 2
Su rango: 2
Sus valores propios:  [0. 1. 1.]


## Actividad 10. Solución de sistemas de ecuaciones lineales
Sea el sistema de ecuaciones $Ax=b$. Hay cuatro posibilidades, a saber:
+ $A$ es una matriz de rango completo, entonces $A^{-1}Ax=A^{-1}b$ de donde $x=A^{-1}b$.
+ $A_{m\times n}$ es una matriz de rango completo por columnas (lo que implica, entre otras cosas, que $m\geq n$), entonces $A'Ax=A'b$ de donde $(A'A)^{-1}A'Ax=(A'A)^{-1}A'b$, luego $x=(A'A)^{-1}A'b$.
+ $A_{m\times n}$ es una matriz de rango completo por filas (lo que implica que $m\leq n$), entonces el sistema tiene múltiples soluciones.
+ $A$ es una matriz de rango incompleto, entonces ni $A$ ni $A'A$ tienen inversa y el sistema puede o no tener solución o tener múltiples soluciones.

In [ ]:
# Conectando con Drive
from google.colab import drive

drive.mount("/content/drive")

Mounted at /content/drive


In [ ]:
# Leyendo un archivo de datos
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/DSRP/Modelos estadísticos/ModEst_Lab1_Datos_1.csv",
                 header=0, sep=";")
display(df)
print(df.dtypes)

y  v1  v2
0    2   0   2
1    3   2   6
2    2   2   7
3    7   2   5
4    6   4   9
5    8   4   8
6   10   4   7
7    7   6  10
8    8   6  11
9   12   6   9
10  11   8  15
11  14   8  13

y     int64
v1    int64
v2    int64
dtype: object


In [ ]:
# Resolviendo el sistema
df['y']
b = np.array(df['y'])
b = b[:, np.newaxis]
A = np.array([np.ones(12), df['v1'], df['v2']])
A = A.T
print("b\n", b)
print("A\n", A)
print("r(A)=", la.matrix_rank(A))

AtA = np.dot(A.T, A)
AtAi = la.inv(AtA)
x = la.multi_dot([AtAi, A.T, b])
print("La solución: ", x)

b
 [[ 2]
 [ 3]
 [ 2]
 [ 7]
 [ 6]
 [ 8]
 [10]
 [ 7]
 [ 8]
 [12]
 [11]
 [14]]
A
 [[ 1.  0.  2.]
 [ 1.  2.  6.]
 [ 1.  2.  7.]
 [ 1.  2.  5.]
 [ 1.  4.  9.]
 [ 1.  4.  8.]
 [ 1.  4.  7.]
 [ 1.  6. 10.]
 [ 1.  6. 11.]
 [ 1.  6.  9.]
 [ 1.  8. 15.]
 [ 1.  8. 13.]]
r(A)= 3
La solución:  [[ 5.37539432]
 [ 3.01182965]
 [-1.28548896]]


## Tarea 1
Investigar sobre el método $\texttt{solve}$ de $\texttt{linalg}$ y resolver el sistema
\begin{eqnarray}
\nonumber \left\{\begin{matrix}
3x_1 + 2x_2 + x_3 & = & 1\\
2x_1 + 2x_2 + 4x_3 & = & -2\\
-x_1 + \frac{1}{2}x_2 -2x_3 & = & 0
\end{matrix}\right.
\end{eqnarray}
¿Qué habría que hacer para resolver el ejemplo anterior usando este método?